var sampleData = {
  id: 1,
	location: 'Atlanta',
	houseType: 'Entire House',
	title: 'Unique Cob Cottage',
	profilePic: 'https://imgur.com/gallery/TaFV6',
	numGuests: 2,
	numBeds: 1,
	numBaths: 1,
	roomType: String,
	numRooms: 3,
	homeHighlights: ['Sparkling clean · 12 recent guests have said that this home was sparkling clean.',
                   'Great check-in experience · 100% of recent guests gave this home’s check-in process a 5-star rating.',
                   'Great location · 100% of recent guests gave this home’s location a 5-star rating.'],
	initDescription: 'Appearing in numerous books on natural building, our cottage is a welcoming and cozy retreat hand sculpted of local, sustainable natural materials located on a lovely acreage with sheep, gardens and orchards.',
	spaceDescription: "Functional loft with a beautiful green and quiet terrace on a classical building in the Roma neighborhood, newly remodeled. The loft has double glazed windows and retractable canvas on the terrace to make the most of natural light and enjoy the pleasant climate of Mexico City.",
	guestAccessDescription: 'Guests have access to the entire cottage and surrounding property.',
	guestInteractionDescription: 'We live in the neighbouring house, and are happy to give advice or answer questions to help you make the most of your stay.',
	otherNotes: "We are happy to offer pickup and drop off at the ferry dock as a courtesy to encourage car-free travellers, on days when the community bus is not running. Please let us know ahead of time that you'll be coming without your own transportation, and we will make sure that either we or the community bus (which will drop you off at our driveway) are there to meet you when your ferry arrives. The BC Ferries terminals near Victoria and Vancouver are easily reachable via public transit from their respective airports and downtowns.",
	ameneties: { 
		basicAmeneties: [{amenity: 'Wifi', description: 'Continuous access'},
		                 {amenity: 'Indoor fireplace', description: ''},
		                 {amenity: 'Laptop friendly workspace', description: 'A table or desk with space for a laptop and a chair that’s comfortable to work in access'},
		                 {amenity: 'Iron', description: ''},
		                 {amenity: 'Hot Water', description: ''},
		                 {amenity: 'Heating', description: 'Central heating or a heater in the listing'},
		                 {amenity: 'Essentials', description: 'Towels, bed sheets, soap, and toilet paper'}],
		familyFeatures: [{amenity: 'Childrens books and toys', description: ''},
		                 {amenity: 'Pack n Play/travel crib', description: ''}],
		facilities: [{amenity: 'Free parking on premises', description: ''}],
		dining: [{amenity: 'Kitchen', description: 'Space where guests can cook their own meals'},
		         {amenity: 'Breakfast', description: 'Breakfast is provided'},
		         {amenity: 'Coffee maker', description: ''},
		         {amenity: 'Cooking basics', description: 'Pots and pans, oil, salt, and pepper'},
		         {amenity: 'Dishes and silverware', description: ''},
		         {amenity: 'Refrigerator', description: ''}],
		guestAccess: [{amenity: 'Lockbox', description: ''},
		              {amenity: 'Private entrance', description: 'Separate street or building entrance'},],
		logistics: [{amenity: 'Luggage dropoff allowed', description: 'For guests convenience when they have early arrival or late departure'},
		           {amenity: 'Long term stays allowed', description: 'Allow stay for 28 days or more'}],
		bedAndBath: [{amenity: 'Bed linens', description: ''},
		             {amenity: 'Extra pillows and blankets', description: ''},
		             {amenity: 'Hair dryer', description: ''},
		             {amenity: 'Hangers', description: ''},
		             {amenity: 'Shampoo', description: ''}],
		outDoor: [{amenity: 'BBQ grill', description: ''},
              {amenity: 'Garden or backyard', description: ''}],
		safetyFeatures: [{amenity: 'Fire extinguisher', description: ''},
                     {amenity: 'Carbon monoxide detector', description: ''}],
		notIncluded: [{amenity: 'Air conditioning', description: ''},
                  {amenity: 'TV', description: ''},
                  {amenity: 'Washer', description: ''}],
	},
	houseRules: {
		list: ['Not suitable for pets',
		       'No parties or events',
		       'Not safe or suitable for children (0-12 years)',
		       'Check-in time is 3PM - 10PM',
		       'Check out by 11AM'],
    description: 'Rather than hard and fast rules, we like to conduct our lives with respect, compassion and consciousness of how our behaviour affects the world around us. Please contact us to chat about coming to the cottage with pets or children or if you would like to plan an event here. We have some safety concerns that we like to make sure you're aware of to make an informed decision. We're always happy to chat about your needs and want you to fall in love with cob building and Mayne island as we have.',
    mustAcknowledge: ['Pets live on property',
                      'Must climb stairs']
	},
	cancellations: {type: 'Strict',
	                description: 'Cancel within 48 hours of booking and 14 days before check-in to get a full refund. Cancel up to 7 days before check in and get a 50% refund (minus service fees). Cancel within 7 days of your trip and the reservation is non-refundable.'},
	accessability: 'Well-lit path to entrance',
	similarListings: [SimilarListingsSchema]