DROP DATABASE IF EXISTS similar;

CREATE DATABASE similar;

USE similar;

CREATE TABLE listings (
  id int NOT NULL AUTO_INCREMENT,
  title varChar(100),
  picture varChar(100),
  houseType varchar(30),
  beds int,
  cost int,
  stars int,
  rating int,
  liked boolean,
  PRIMARY KEY (ID)
);

CREATE TABLE lists (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(40),
  PRIMARY KEY (ID)
);

CREATE TABLE lists2listings (
  listingId int NOT NULL,
  listId int NOT NULL,
  PRIMARY KEY (listingId, listId)
);

insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (1, 'Multi-layered 24/7 methodology', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_200.jpg', 'Safari', 3, 103, 4, 140, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (2, 'Business-focused explicit infrastructure', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_201.jpg', 'VUE', 3, 185, 3, 66, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (3, 'Streamlined 24 hour approach', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_202.jpg', 'Thunderbird', 4, 112, 4, 124, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (4, 'Function-based bandwidth-monitored artificial intelligence', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_203.jpg', 'Vandura 3500', 3, 113, 5, 240, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (5, 'Upgradable real-time hub', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_204.jpg', 'Sonata', 2, 244, 5, 112, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (6, 'Streamlined contextually-based middleware', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_205.jpg', 'Esprit', 3, 133, 4, 147, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (7, 'Object-based radical local area network', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_206.jpg', 'Rabbit', 3, 203, 3, 219, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (8, 'Seamless bottom-line product', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_207.jpg', 'E-Series', 4, 213, 3, 229, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (9, 'Inverse bifurcated process improvement', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_208.jpg', '9-4X', 4, 196, 5, 1, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (10, 'Mandatory responsive open system', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_209.jpg', 'Passat', 1, 60, 4, 221, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (11, 'Devolved directional capacity', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_210.jpg', 'Forester', 4, 150, 4, 30, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (12, 'Versatile impactful time-frame', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_211.jpg', '1500', 2, 165, 5, 156, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (13, 'Synergized multimedia process improvement', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_212.jpg', 'Express 2500', 1, 211, 5, 188, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (14, 'Sharable system-worthy software', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_213.jpg', 'CR-V', 3, 107, 5, 77, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (15, 'De-engineered dedicated support', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_214.jpg', 'xB', 1, 83, 5, 209, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (16, 'Proactive content-based approach', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_215.jpg', 'Tredia', 1, 146, 4, 95, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (17, 'Enhanced optimal framework', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_216.jpg', 'Impreza', 2, 86, 4, 60, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (18, 'Implemented content-based methodology', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_217.jpg', 'E-Series', 4, 68, 3, 45, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (19, 'Enterprise-wide attitude-oriented hardware', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_218.jpg', 'RAV4', 3, 190, 5, 84, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (20, 'Pre-emptive scalable portal', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_219.jpg', 'Terrain', 4, 232, 4, 29, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (21, 'Profit-focused needs-based instruction set', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_220.jpg', 'ZDX', 2, 58, 3, 37, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (22, 'Down-sized fresh-thinking interface', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_221.jpg', 'Vitara', 1, 138, 3, 65, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (23, 'Profound multimedia help-desk', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_222.jpg', 'Murciélago', 1, 215, 3, 22, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (24, 'Phased needs-based adapter', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_223.jpg', 'B9 Tribeca', 3, 138, 3, 206, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (25, 'Mandatory zero administration hardware', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_224.jpg', 'RS 4', 1, 188, 5, 58, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (26, 'Distributed systematic encoding', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_225.jpg', 'Town Car', 1, 165, 5, 178, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (27, 'Multi-lateral client-driven middleware', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_226.jpg', 'Cavalier', 4, 171, 3, 118, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (28, 'Triple-buffered well-modulated extranet', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_227.jpg', 'MKX', 4, 167, 4, 204, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (29, 'Integrated high-level process improvement', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_228.jpg', 'Oasis', 2, 146, 4, 119, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (30, 'Streamlined needs-based budgetary management', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_229.jpg', 'E-Series', 2, 177, 5, 182, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (31, 'Ergonomic client-driven toolset', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_230.jpg', 'Aerostar', 1, 136, 4, 218, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (32, 'Business-focused homogeneous Graphic Interface', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_231.jpg', 'Oasis', 3, 190, 5, 165, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (33, 'Centralized empowering monitoring', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_232.jpg', 'CL-Class', 1, 77, 3, 28, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (34, 'Cloned high-level productivity', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_233.jpg', 'MX-3', 3, 155, 5, 124, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (35, 'Ameliorated tertiary forecast', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_234.jpg', '900', 4, 65, 4, 9, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (36, 'Networked value-added emulation', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_235.jpg', 'Supra', 3, 108, 4, 183, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (37, 'Extended logistical focus group', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_236.jpg', 'Range Rover', 3, 235, 5, 14, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (38, 'Managed secondary initiative', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_237.jpg', 'Evora', 3, 61, 3, 10, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (39, 'Open-architected incremental framework', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_238.jpg', 'Miata MX-5', 4, 200, 5, 3, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (40, 'Synergistic transitional projection', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_239.jpg', 'Ram Van 3500', 2, 138, 4, 40, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (41, 'Re-contextualized dedicated policy', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_240.jpg', 'S80', 1, 102, 3, 165, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (42, 'Public-key context-sensitive definition', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_241.jpg', 'Cooper', 3, 230, 5, 250, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (43, 'Focused content-based parallelism', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_242.jpg', 'Tacoma Xtra', 2, 213, 4, 92, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (44, 'Front-line modular capacity', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_243.jpg', 'Montana SV6', 2, 200, 5, 207, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (45, 'Synergized responsive middleware', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_244.jpg', 'Cavalier', 4, 66, 5, 207, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (46, 'Ameliorated dynamic workforce', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_245.jpg', 'Focus', 3, 231, 3, 216, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (47, 'Down-sized directional model', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_246.jpg', 'TundraMax', 1, 147, 5, 73, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (48, 'Up-sized human-resource matrices', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_247.jpg', 'Reno', 1, 216, 3, 78, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (49, 'Devolved attitude-oriented encryption', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_248.jpg', 'Trans Sport', 4, 206, 4, 149, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (50, 'User-friendly needs-based moratorium', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_249.jpg', 'Ram 1500 Club', 3, 90, 3, 196, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (51, 'Multi-lateral eco-centric architecture', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_250.jpg', 'xA', 3, 134, 4, 138, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (52, 'Cloned multi-tasking data-warehouse', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_251.jpg', 'Pajero', 3, 232, 4, 64, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (53, 'Realigned background structure', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_252.jpg', 'Crown Victoria', 2, 64, 5, 152, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (54, 'De-engineered actuating synergy', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_253.jpg', 'Type-1h', 3, 128, 5, 110, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (55, 'Visionary methodical definition', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_254.jpg', 'Ram 3500', 1, 56, 4, 139, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (56, 'Networked mission-critical focus group', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_255.jpg', 'Escort', 3, 185, 4, 172, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (57, 'Customer-focused needs-based groupware', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_256.jpg', '599 GTB Fiorano', 2, 86, 5, 114, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (58, 'Progressive radical project', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_257.jpg', '7 Series', 1, 102, 3, 222, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (59, 'Horizontal intangible infrastructure', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_258.jpg', 'V70', 3, 164, 4, 204, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (60, 'Function-based systemic parallelism', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_259.jpg', 'Grand Am', 4, 182, 3, 246, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (61, 'Up-sized multi-state frame', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_260.jpg', 'Sierra 2500HD', 4, 237, 4, 162, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (62, 'Balanced actuating artificial intelligence', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_261.jpg', 'M', 1, 89, 5, 58, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (63, 'Assimilated human-resource complexity', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_262.jpg', 'Eclipse', 1, 219, 5, 191, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (64, 'Programmable next generation budgetary management', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_263.jpg', 'Highlander', 1, 172, 5, 195, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (65, 'Switchable object-oriented initiative', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_264.jpg', 'Contour', 3, 117, 4, 62, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (66, 'Open-architected bifurcated circuit', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_265.jpg', 'Talon', 4, 65, 3, 94, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (67, 'Focused value-added secured line', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_266.jpg', 'Cooper', 4, 122, 5, 101, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (68, 'Re-engineered static service-desk', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_267.jpg', 'Silverado 1500', 2, 89, 4, 198, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (69, 'Synergistic asymmetric knowledge user', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_268.jpg', 'RX-7', 4, 172, 3, 91, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (70, 'Monitored mission-critical firmware', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_269.jpg', 'Daewoo Lacetti', 3, 87, 5, 136, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (71, 'Managed directional hub', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_270.jpg', 'Jetta', 3, 206, 5, 65, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (72, 'Synergistic cohesive moderator', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_271.jpg', 'Passat', 1, 247, 3, 219, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (73, 'Advanced human-resource initiative', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_272.jpg', 'Samurai', 1, 116, 3, 26, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (74, 'Distributed user-facing algorithm', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_273.jpg', 'Taurus', 2, 154, 3, 166, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (75, 'Ergonomic static circuit', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_274.jpg', 'F430', 2, 186, 3, 118, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (76, 'Phased contextually-based moratorium', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_275.jpg', 'Eclipse', 1, 115, 3, 118, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (77, 'Synchronised bifurcated standardization', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_276.jpg', 'Fit', 4, 192, 3, 199, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (78, 'Down-sized well-modulated process improvement', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_277.jpg', 'Golf', 4, 137, 5, 8, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (79, 'Upgradable empowering customer loyalty', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_278.jpg', '599 GTB Fiorano', 3, 78, 5, 167, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (80, 'Business-focused web-enabled service-desk', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_279.jpg', 'Sebring', 1, 87, 3, 33, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (81, 'Reactive value-added leverage', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_280.jpg', 'Daytona', 2, 212, 5, 119, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (82, 'Multi-tiered uniform attitude', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_281.jpg', 'Escort ZX2', 2, 182, 3, 55, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (83, 'Stand-alone optimal focus group', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_282.jpg', 'Intrepid', 4, 234, 4, 228, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (84, 'Function-based 24/7 pricing structure', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_283.jpg', 'Explorer', 3, 204, 3, 188, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (85, 'Exclusive background knowledge user', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_284.jpg', 'Spirit', 4, 84, 5, 204, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (86, 'Customizable mobile knowledge user', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_285.jpg', 'Sonata', 3, 104, 5, 138, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (87, 'Ameliorated asynchronous methodology', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_286.jpg', 'Aero 8', 4, 171, 5, 152, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (88, 'User-centric modular open architecture', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_287.jpg', 'Maxima', 2, 209, 4, 189, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (89, 'Customer-focused needs-based analyzer', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_288.jpg', 'Town Car', 1, 138, 5, 224, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (90, 'Programmable static monitoring', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_289.jpg', 'RSX', 4, 141, 3, 14, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (91, 'Programmable full-range budgetary management', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_290.jpg', 'Navigator', 2, 119, 3, 169, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (92, 'Managed optimal customer loyalty', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_291.jpg', 'Grand Prix', 3, 58, 5, 204, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (93, 'Compatible multi-tasking forecast', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_292.jpg', '3000GT', 4, 176, 5, 57, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (94, 'Adaptive high-level ability', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_293.jpg', 'Equinox', 1, 234, 3, 168, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (95, 'Function-based didactic framework', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_294.jpg', 'Corvette', 3, 195, 3, 46, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (96, 'Extended eco-centric Graphic Interface', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_295.jpg', 'S40', 1, 164, 4, 173, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (97, 'Monitored asymmetric firmware', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_296.jpg', 'Flex', 3, 244, 4, 44, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (98, 'Re-contextualized reciprocal instruction set', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_297.jpg', 'Diablo', 3, 123, 3, 1, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (99, 'Compatible cohesive infrastructure', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_298.jpg', 'XJ Series', 4, 115, 5, 14, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (100, 'Implemented zero defect hardware', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_299.jpg', 'Ram 3500', 3, 198, 5, 134, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (101, 'Diverse zero tolerance initiative', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_300.jpg', 'F350', 3, 189, 3, 182, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (102, 'Synergized holistic migration', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_301.jpg', 'RAV4', 4, 145, 3, 212, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (103, 'Reduced exuding frame', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_302.jpg', 'Explorer', 1, 190, 5, 227, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (104, 'Persevering intangible methodology', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_303.jpg', 'Crown Victoria', 4, 57, 5, 239, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (105, 'Visionary responsive knowledge user', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_304.jpg', 'XF', 2, 73, 5, 250, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (106, 'Ergonomic executive database', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_305.jpg', 'LTD Crown Victoria', 2, 133, 4, 131, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (107, 'Function-based attitude-oriented framework', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_306.jpg', 'F150', 1, 93, 4, 90, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (108, 'Persevering reciprocal toolset', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_307.jpg', 'GTI', 3, 159, 4, 168, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (109, 'Balanced reciprocal orchestration', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_308.jpg', 'Azera', 4, 148, 5, 250, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (110, 'Virtual composite emulation', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_309.jpg', 'SC', 3, 184, 5, 16, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (111, 'Pre-emptive object-oriented strategy', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_310.jpg', 'Swift', 1, 59, 4, 159, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (112, 'Operative asynchronous utilisation', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_311.jpg', 'Eclipse', 2, 216, 5, 92, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (113, 'Pre-emptive coherent Graphic Interface', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_312.jpg', 'Aura', 4, 181, 4, 8, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (114, 'Phased full-range framework', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_313.jpg', 'Venture', 4, 98, 3, 170, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (115, 'Universal systemic knowledge base', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_314.jpg', 'TrailBlazer', 1, 227, 4, 179, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (116, 'Diverse demand-driven application', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_315.jpg', 'RSX', 4, 97, 3, 248, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (117, 'Managed uniform open architecture', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_316.jpg', 'Tiburon', 4, 206, 4, 77, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (118, 'Compatible encompassing attitude', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_317.jpg', 'Aztek', 4, 124, 4, 2, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (119, 'Reduced context-sensitive parallelism', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_318.jpg', 'RL', 4, 249, 3, 136, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (120, 'Intuitive hybrid moratorium', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_319.jpg', 'Grand Caravan', 1, 189, 4, 161, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (121, 'Reactive explicit architecture', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_320.jpg', 'Grand Prix', 2, 55, 4, 12, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (122, 'Secured motivating forecast', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_321.jpg', 'Cooper Clubman', 3, 122, 3, 107, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (123, 'Vision-oriented client-server flexibility', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_322.jpg', 'Aura', 3, 117, 3, 2, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (124, 'Customizable mission-critical help-desk', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_323.jpg', 'Bravada', 2, 190, 5, 220, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (125, 'Automated mobile matrices', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_324.jpg', 'GT', 4, 55, 5, 175, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (126, 'Implemented upward-trending strategy', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_325.jpg', 'Murciélago', 3, 218, 3, 56, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (127, 'Upgradable mobile contingency', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_326.jpg', 'Escalade EXT', 4, 102, 5, 60, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (128, 'Fully-configurable bottom-line moratorium', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_327.jpg', 'Aspire', 3, 228, 4, 172, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (129, 'Synchronised holistic model', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_328.jpg', 'C70', 1, 81, 5, 104, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (130, 'Universal regional knowledge base', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_329.jpg', 'STS', 1, 196, 3, 39, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (131, 'Expanded directional challenge', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_330.jpg', 'Cayenne', 3, 74, 5, 9, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (132, 'Re-contextualized value-added infrastructure', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_331.jpg', 'SC', 4, 243, 4, 100, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (133, 'Horizontal contextually-based software', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_332.jpg', 'Golf', 4, 185, 5, 164, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (134, 'Profound stable forecast', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_333.jpg', 'Forester', 3, 171, 4, 94, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (135, 'Ergonomic secondary architecture', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_334.jpg', '5000CS', 3, 147, 4, 179, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (136, 'Ergonomic optimal paradigm', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_335.jpg', 'ES', 1, 171, 3, 168, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (137, 'Centralized modular moratorium', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_336.jpg', 'Charger', 1, 146, 5, 236, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (138, 'Persistent methodical application', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_337.jpg', 'Montero', 1, 98, 4, 125, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (139, 'Cross-group incremental benchmark', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_338.jpg', 'E250', 3, 158, 4, 76, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (140, 'Focused bottom-line matrix', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_339.jpg', 'Caprice Classic', 3, 80, 3, 238, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (141, 'Exclusive contextually-based pricing structure', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_340.jpg', 'Arnage', 4, 69, 4, 217, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (142, 'Compatible clear-thinking policy', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_341.jpg', 'Eclipse', 1, 227, 5, 227, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (143, 'Operative multi-state open architecture', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_342.jpg', '924', 4, 237, 5, 95, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (144, 'Public-key asymmetric paradigm', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_343.jpg', 'Arnage', 1, 208, 5, 26, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (145, 'Configurable 6th generation adapter', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_344.jpg', 'Phaeton', 2, 148, 4, 155, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (146, 'Right-sized clear-thinking local area network', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_345.jpg', 'Range Rover Evoque', 1, 149, 3, 11, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (147, 'Multi-lateral value-added knowledge base', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_346.jpg', 'Eldorado', 1, 185, 4, 105, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (148, 'Down-sized multi-tasking success', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_347.jpg', 'I', 2, 184, 5, 65, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (149, 'Synergistic 24/7 process improvement', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_348.jpg', 'Solara', 1, 223, 3, 5, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (150, 'Optional next generation knowledge base', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_349.jpg', 'Legacy', 1, 87, 5, 137, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (151, 'Synchronised asynchronous infrastructure', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_350.jpg', 'Yukon', 4, 164, 5, 132, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (152, 'Balanced zero defect forecast', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_351.jpg', 'Grand Prix', 2, 154, 5, 239, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (153, 'Open-architected executive methodology', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_352.jpg', 'Continental Mark VII', 4, 147, 3, 42, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (154, 'Cross-platform solution-oriented hardware', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_353.jpg', 'SVX', 1, 96, 4, 189, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (155, 'Up-sized 24 hour throughput', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_354.jpg', 'V50', 1, 71, 4, 56, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (156, 'Synergistic stable synergy', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_355.jpg', 'I', 3, 159, 5, 227, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (157, 'Organized explicit conglomeration', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_356.jpg', 'A6', 1, 181, 5, 51, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (158, 'Re-contextualized context-sensitive conglomeration', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_357.jpg', 'Galant', 4, 71, 3, 13, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (159, 'Upgradable fault-tolerant solution', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_358.jpg', 'Range Rover', 3, 115, 5, 25, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (160, 'Focused mobile orchestration', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_359.jpg', 'Tacoma Xtra', 2, 230, 5, 24, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (161, 'Customizable radical standardization', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_360.jpg', 'Grand Prix', 2, 208, 3, 185, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (162, 'Realigned impactful product', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_361.jpg', 'F350', 2, 110, 3, 236, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (163, 'Robust 24 hour attitude', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_362.jpg', 'TSX', 3, 103, 5, 130, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (164, 'Optional grid-enabled artificial intelligence', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_363.jpg', 'M5', 4, 247, 5, 51, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (165, 'Horizontal fresh-thinking collaboration', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_364.jpg', 'Impreza', 3, 72, 5, 166, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (166, 'Future-proofed exuding strategy', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_365.jpg', 'Regal', 1, 216, 3, 44, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (167, 'Open-architected context-sensitive local area network', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_366.jpg', 'S4', 2, 176, 3, 176, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (168, 'Multi-layered stable structure', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_367.jpg', 'Corvette', 1, 195, 3, 134, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (169, 'Universal scalable attitude', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_368.jpg', 'Starion', 2, 149, 3, 193, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (170, 'Pre-emptive multi-tasking forecast', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_369.jpg', 'Esteem', 2, 106, 3, 246, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (171, 'Quality-focused transitional leverage', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_370.jpg', 'Accent', 1, 165, 5, 82, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (172, 'Polarised leading edge moratorium', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_371.jpg', 'LS', 2, 120, 5, 83, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (173, 'Fundamental empowering utilisation', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_372.jpg', 'Trooper', 1, 57, 3, 133, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (174, 'Expanded reciprocal contingency', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_373.jpg', 'Escort', 4, 240, 3, 65, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (175, 'Horizontal non-volatile firmware', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_374.jpg', 'Explorer Sport Trac', 2, 211, 5, 199, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (176, 'Synergized intermediate workforce', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_375.jpg', 'Solara', 1, 226, 5, 61, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (177, 'Upgradable client-driven frame', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_376.jpg', 'Leaf', 1, 138, 5, 37, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (178, 'Organized well-modulated service-desk', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_377.jpg', 'SL-Class', 4, 210, 5, 60, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (179, 'Optional optimal Graphic Interface', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_378.jpg', 'IS', 4, 82, 3, 217, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (180, 'Quality-focused background synergy', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_379.jpg', 'Sportvan G30', 4, 212, 4, 186, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (181, 'Ameliorated asymmetric knowledge user', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_380.jpg', 'Xterra', 4, 220, 4, 168, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (182, 'Synergized global software', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_381.jpg', 'Bravada', 1, 91, 4, 52, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (183, 'Diverse full-range project', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_382.jpg', 'Tahoe', 4, 173, 5, 188, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (184, 'Optional web-enabled help-desk', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_383.jpg', 'M-Class', 2, 105, 5, 2, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (185, 'Sharable secondary hierarchy', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_384.jpg', '968', 1, 156, 5, 240, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (186, 'Polarised heuristic initiative', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_385.jpg', 'A6', 1, 152, 3, 214, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (187, 'Secured 5th generation synergy', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_386.jpg', 'Skylark', 1, 109, 3, 93, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (188, 'Decentralized 5th generation structure', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_387.jpg', 'TrailBlazer', 4, 170, 5, 33, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (189, 'Reverse-engineered impactful budgetary management', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_388.jpg', 'Escalade EXT', 3, 250, 5, 217, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (190, 'Devolved systematic middleware', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_389.jpg', 'Cube', 1, 68, 5, 145, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (191, 'Phased context-sensitive moderator', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_390.jpg', 'Quattroporte', 2, 102, 5, 178, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (192, 'Ameliorated modular focus group', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_391.jpg', '8 Series', 3, 159, 3, 208, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (193, 'Multi-tiered foreground extranet', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_392.jpg', 'Lancer', 3, 227, 4, 241, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (194, 'Customizable even-keeled task-force', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_393.jpg', 'Sentra', 3, 69, 4, 186, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (195, 'Down-sized 6th generation software', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_394.jpg', 'Colorado', 2, 112, 4, 63, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (196, 'Face to face zero tolerance core', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_395.jpg', 'Axiom', 2, 77, 4, 177, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (197, 'Decentralized mission-critical solution', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_396.jpg', 'Silverado 1500', 4, 173, 4, 63, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (198, 'De-engineered fault-tolerant application', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_397.jpg', 'Corvette', 3, 220, 5, 43, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (199, 'Stand-alone intangible concept', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_398.jpg', 'Sierra 1500', 3, 239, 3, 229, false);
insert into listings (id, title, picture, houseType, beds, cost, stars, rating, liked) values (200, 'Enterprise-wide stable interface', 'https://s3-us-west-1.amazonaws.com/sharebnbphotos/house_photo_399.jpg', 'X-Type', 3, 146, 4, 49, false);
